# Generated by Django 5.0.1 on 2024-08-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_login', '0027_alter_pendingprovider_category_and_more'),
        ('provider_details', '0027_coupon_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavorateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_login.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.product')),
            ],
        ),
        migrations.CreateModel(
            name='FavorateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_login.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.service')),
            ],
        ),
    ]
