# Generated by Django 5.0.1 on 2024-08-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorateservice',
            old_name='product',
            new_name='service',
        ),
    ]
