# Generated by Django 5.0.1 on 2024-08-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0027_alter_pendingprovider_category_and_more'),
        ('client', '0002_rename_product_favorateservice_service'),
        ('provider_details', '0027_coupon_provider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorateproduct',
            unique_together={('product', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='favorateservice',
            unique_together={('service', 'customer')},
        ),
    ]
