# Generated by Django 4.2.6 on 2023-12-09 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_login', '0001_initial'),
        ('categroy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/provider/store/', verbose_name='رفع الصورة')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المتجر')),
                ('about', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث')),
                ('Provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_login.provider')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموظف')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255, verbose_name='اليوم')),
                ('time_start', models.TimeField(verbose_name='وقت البدء')),
                ('time_end', models.TimeField(verbose_name='وقت الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/provider/gallery/', verbose_name='رفع الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreAdminServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categroy.mainservice')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.store')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/provider/service/', verbose_name='رفع الصورة')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('offers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الخصم')),
                ('hours_Service', models.TextField(blank=True, null=True, verbose_name='ساعات الخدمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/provider/service/', verbose_name='رفع الصورة')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('offers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الخصم')),
                ('hours_Service', models.TextField(blank=True, null=True, verbose_name='ساعات الخدمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.store')),
            ],
        ),
    ]
