# Generated by Django 4.2.6 on 2023-12-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categroy', '0001_initial'),
        ('provider_details', '0002_rename_provider_store_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='main_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categroy.mainservice'),
        ),
    ]
