# Generated by Django 4.2.6 on 2023-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0004_alter_product_hours_service_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='السعر'),
        ),
    ]
