# Generated by Django 4.2.6 on 2023-12-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categroy', '0001_initial'),
        ('provider_details', '0006_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeadminservices',
            name='main_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categroy.mainservice'),
        ),
    ]
