# Generated by Django 4.2.6 on 2023-12-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0009_storestory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeadminservices',
            options={'verbose_name_plural': 'Services for Store'},
        ),
    ]
