# Generated by Django 4.2.6 on 2023-12-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0010_alter_storeadminservices_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
    ]
