# Generated by Django 5.0.1 on 2024-01-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0012_storespecialist_phone_specialistworks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistworks',
            options={'verbose_name_plural': 'Main services  for specialist'},
        ),
        migrations.RemoveField(
            model_name='specialistworks',
            name='specialist',
        ),
        migrations.AddField(
            model_name='storespecialist',
            name='specialistworks',
            field=models.ManyToManyField(to='provider_details.specialistworks'),
        ),
    ]
