# Generated by Django 5.0.1 on 2024-01-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categroy', '0001_initial'),
        ('provider_details', '0013_alter_specialistworks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storespecialist',
            name='specialistworks',
            field=models.ManyToManyField(to='categroy.mainservice'),
        ),
    ]
