# Generated by Django 5.0.1 on 2024-02-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0014_alter_storespecialist_specialistworks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialistWorks',
        ),
    ]
