# Generated by Django 5.0.1 on 2024-02-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0015_delete_specialistworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='storespecialist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/provider/store/', verbose_name='رفع الصورة'),
        ),
    ]
