# Generated by Django 5.0.1 on 2024-03-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0019_remove_service_hours_service_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='specialists',
            field=models.ManyToManyField(to='provider_details.storespecialist'),
        ),
    ]
