# Generated by Django 5.0.1 on 2024-03-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0020_service_specialists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/provider/service/', verbose_name='رفع الصورة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/provider/service/', verbose_name='رفع الصورة'),
        ),
    ]
