# Generated by Django 5.0.1 on 2024-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0024_remove_product_hours_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='whatsapp_link',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
