# Generated by Django 5.0.1 on 2024-07-19 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0027_alter_pendingprovider_category_and_more'),
        ('provider_details', '0026_commonquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_login.provider'),
            preserve_default=False,
        ),
    ]
