# Generated by Django 5.0.1 on 2024-08-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0027_coupon_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeopening',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15, verbose_name='اليوم'),
        ),
    ]
