# Generated by Django 5.0.1 on 2024-02-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0002_adminuser_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Subscription date')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('profit_ratio', models.IntegerField(default=0, verbose_name='معدل الربح')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_login.provider', verbose_name='provider')),
            ],
        ),
    ]
