# Generated by Django 5.0.1 on 2024-02-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0003_providersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersubscription',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Subscription date'),
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='profit_ratio',
            field=models.IntegerField(default=0, verbose_name=' Profit Ratio'),
        ),
    ]
