# Generated by Django 5.0.1 on 2024-02-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0005_alter_providersubscription_profit_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providersubscription',
            name='profit_ratio',
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Subscription date'),
        ),
    ]
