# Generated by Django 5.0.1 on 2024-02-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0006_remove_providersubscription_profit_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersubscription',
            name='profit_ratio',
            field=models.IntegerField(default=0, verbose_name='Profit Ratio'),
        ),
    ]
