# Generated by Django 5.0.1 on 2024-02-06 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0007_providersubscription_profit_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersubscription',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_login.provider', verbose_name='provider'),
        ),
    ]
