# Generated by Django 5.0.1 on 2024-02-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0008_alter_providersubscription_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providersubscription',
            name='profit_ratio',
        ),
        migrations.AddField(
            model_name='providersubscription',
            name='product_profit',
            field=models.IntegerField(default=0, verbose_name='product profit'),
        ),
        migrations.AddField(
            model_name='providersubscription',
            name='service_profit',
            field=models.IntegerField(default=0, verbose_name='service profit'),
        ),
        migrations.AddField(
            model_name='providersubscription',
            name='store_subscription',
            field=models.BooleanField(default=True, verbose_name='store subscription'),
            preserve_default=False,
        ),
    ]
