# Generated by Django 5.0.1 on 2024-02-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0009_remove_providersubscription_profit_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersubscription',
            name='promotion_date',
            field=models.DateField(null=True, verbose_name='Promotion start date'),
        ),
        migrations.AddField(
            model_name='providersubscription',
            name='promotion_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Promotion Duration'),
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='duration',
            field=models.DurationField(choices=[(90, '90 days'), (180, '180 days'), (365, '365 days')], verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='product_profit',
            field=models.IntegerField(blank=True, default=0, verbose_name='product profit'),
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='store_subscription',
            field=models.BooleanField(default=False, verbose_name='store subscription'),
        ),
    ]
