# Generated by Django 5.0.1 on 2024-02-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0011_remove_providersubscription_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersubscription',
            name='date',
            field=models.DateField(verbose_name='Subscription date'),
        ),
    ]
