# Generated by Django 5.0.1 on 2024-02-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0012_alter_providersubscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersubscription',
            name='promotion_subscription',
            field=models.BooleanField(default=False, verbose_name='Promotion subscription'),
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='promotion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Promotion start date'),
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='store_subscription',
            field=models.BooleanField(default=False, verbose_name='Store subscription'),
        ),
    ]
