# Generated by Django 5.0.1 on 2024-02-11 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0013_providersubscription_promotion_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providersubscription',
            name='promotion_date',
        ),
        migrations.RemoveField(
            model_name='providersubscription',
            name='promotion_duration',
        ),
        migrations.RemoveField(
            model_name='providersubscription',
            name='promotion_subscription',
        ),
        migrations.CreateModel(
            name='PromotionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField(blank=True, null=True, verbose_name='Promotion start date')),
                ('promotion_duration_days', models.IntegerField(blank=True, choices=[(15, '15 days'), (30, '30 days'), (45, '45 days')], null=True, verbose_name='Promotion Duration')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_login.provider', verbose_name='provider')),
            ],
        ),
    ]
