# Generated by Django 5.0.1 on 2024-03-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0014_remove_providersubscription_promotion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionsubscription',
            name='profit',
            field=models.IntegerField(blank=True, default=0, verbose_name='product profit'),
        ),
        migrations.AlterField(
            model_name='promotionsubscription',
            name='promotion_duration_days',
            field=models.IntegerField(blank=True, choices=[(3, '3 days'), (7, '7 days'), (15, '15 days'), (30, '30 days'), (45, '45 days')], null=True, verbose_name='Promotion Duration'),
        ),
    ]
