# Generated by Django 5.0.1 on 2024-03-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0015_promotionsubscription_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersubscription',
            name='duration_days',
            field=models.IntegerField(choices=[(30, '30 days'), (60, '60 days'), (90, '90 days'), (180, '180 days'), (365, '365 days'), (730, '730 days')], verbose_name='Duration'),
        ),
    ]
