# Generated by Django 5.0.1 on 2024-05-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0019_alter_myuser_email_alter_promotionsubscription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=9, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
