# Generated by Django 5.0.1 on 2024-06-02 19:33

import auth_login.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0021_alter_adminuser_managers_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('code', models.CharField(default=auth_login.models.otpCodeDefault, max_length=4)),
                ('expireAt', models.DateTimeField(default=auth_login.models.expireDefault)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('REGISTER', 'Register'), ('RESET_PHONE', 'Reset Phone'), ('FORGET_PASSWORD', 'Forget Password')], max_length=18)),
                ('isUsed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PendingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('otp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendingClient', to='auth_login.otprequest')),
            ],
        ),
    ]
