# Generated by Django 5.0.1 on 2024-06-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0022_otprequest_pendingclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
