# Generated by Django 5.0.1 on 2024-06-07 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0024_remove_pendingclient_password_pendingprovider'),
        ('categroy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingprovider',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='categroy.category'),
            preserve_default=False,
        ),
    ]
