# Generated by Django 5.0.1 on 2024-06-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0025_pendingprovider_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingprovider',
            name='otp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendingProvider', to='auth_login.otprequest'),
        ),
    ]
