# Generated by Django 5.0.1 on 2024-08-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0027_alter_pendingprovider_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/customers/'),
        ),
    ]
