# Generated by Django 4.2.6 on 2023-12-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_login', '0001_initial'),
        ('provider_details', '0005_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(blank=True, default=False, null=True, verbose_name='موافقة التاجر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_login.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.service')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(blank=True, default=False, null=True, verbose_name='موافقة التاجر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_login.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.product')),
            ],
        ),
    ]
