# Generated by Django 4.2.6 on 2023-12-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0011_storestory_created_at'),
        ('order_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحجز'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='مدة الخدمة'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider_details.storespecialist'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='time_start',
            field=models.TimeField(null=True, verbose_name='وقت البدء'),
        ),
    ]
