# Generated by Django 5.0.1 on 2024-02-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0014_remove_providersubscription_promotion_date_and_more'),
        ('order_cart', '0002_serviceorder_date_serviceorder_duration_and_more'),
        ('provider_details', '0018_alter_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_login.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.product')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('time_start', models.TimeField(null=True, verbose_name='وقت البدء')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحجز')),
                ('duration', models.TimeField(blank=True, null=True, verbose_name='مدة الخدمة')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_cart.cart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_details.service')),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider_details.storespecialist')),
            ],
        ),
    ]
