# Generated by Django 5.0.1 on 2024-02-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0003_cart_cartitem_servicecartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecartitem',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='مدة الخدمة'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='مدة الخدمة'),
        ),
    ]
