# Generated by Django 5.0.1 on 2024-02-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0007_alter_serviceorder_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
