# Generated by Django 5.0.1 on 2024-03-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0009_productorder_collected_serviceorder_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
    ]
