# Generated by Django 5.0.1 on 2024-04-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0010_productorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='accomplished',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تم انجازه'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='accomplished',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تم انجازه'),
        ),
    ]
