# Generated by Django 5.0.1 on 2024-07-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0011_productorder_accomplished_serviceorder_accomplished'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='canceled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ملغي'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='rejected',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=' مرفوض'),
        ),
    ]
