# Generated by Django 5.0.1 on 2024-07-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0012_serviceorder_canceled_serviceorder_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='canceled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ملغي'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='rejected',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=' مرفوض'),
        ),
    ]
