# Generated by Django 5.0.1 on 2024-07-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0013_productorder_canceled_productorder_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='accomplished',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='rejected',
        ),
        migrations.AddField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
