# Generated by Django 5.0.1 on 2024-07-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0015_remove_serviceorder_accept_and_more'),
        ('provider_details', '0026_commonquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider_details.coupon'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider_details.coupon'),
        ),
    ]
