# Generated by Django 5.0.1 on 2024-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0017_alter_productorder_status_alter_serviceorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='media/order/qr_code'),
        ),
    ]
