# Generated by Django 5.0.1 on 2024-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0018_serviceorder_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='media/order/qr_code'),
        ),
    ]
